# Generelle Einstellungen, zu dem Spielprinzip und verschiedenen Features
general:
  reset: false
  gameName: Bingo
  prefix: '§8| §bBINGO§8 §8» §7'
  colorcode: '§c'

# Einstellungen, zur Manipulation vom Aussehen des Plugins
lang:
  commandNotReady: '§cDieser Command ist nur während des Spiels freigeschaltet!'
  resetKickMessage: '§cDer Server wurde resettet! \n§7Du wurdest deshalb gekickt!'
  noPermission: '§cDu hast keine Rechte für diesen Befehl!'
  noTeamOnStart: '§cDa du kein Team ausgewählt hast wurdest du leider gekickt!'
  noMember: '§cDu bist keine Teilnehmer dieses Bingos!'
  buildModeJoin: '§7Du hast den §bBau-Modus §betreten!'
  buildModeQuit: '§7Du hast den §bBau-Modus §7verlassen!'
