name: Bingo
version: 1.0
author: yNikk
main: eu.flowtex.bingo.Main
description: Bingo - Made for the Flowtex.eu Plugin Shop
api-version: 1.16
load: STARTUP
commands:
  items:
  bingo:
  top:
  reset:
